name: Build and Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew
      shell: bash

    - name: Generate build number
      id: build_number
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_OUTPUT
        echo "Build number: $BUILD_NUMBER"
      shell: bash

    - name: Update version in build.gradle
      run: |
        BUILD_NUMBER=${{ steps.build_number.outputs.BUILD_NUMBER }}
        sed -i "s/version = '1.0-SNAPSHOT'/version = '1.0.$BUILD_NUMBER'/" build.gradle
      shell: bash

    - name: Update version in plugin.yml
      run: |
        BUILD_NUMBER=${{ steps.build_number.outputs.BUILD_NUMBER }}
        sed -i "s/version: '1.0-SNAPSHOT'/version: '1.0.$BUILD_NUMBER'/" src/main/resources/plugin.yml
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash

    - name: Get commit messages
      id: commits
      run: |
        REPO_URL="https://github.com/${{ github.repository }}"
        if [ "${{ github.event_name }}" == "push" ]; then
          COMMITS=$(git log --pretty=format:"- [%H] %s ([View commit]($REPO_URL/commit/%H))" ${{ github.event.before }}..${{ github.sha }} | head -20)
        else
          COMMITS=$(git log --pretty=format:"- [%H] %s ([View commit]($REPO_URL/commit/%H))" -10)
        fi
        echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMITS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Find JAR file
      id: jar_file
      run: |
        JAR_FILE=$(find build/libs -name "*.jar" -type f | head -1)
        JAR_NAME=$(basename "$JAR_FILE")
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_OUTPUT
        echo "Found JAR: $JAR_FILE"
      shell: bash

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        name: Build ${{ steps.build_number.outputs.BUILD_NUMBER }}
        tag_name: v1.0.0
        files: build/libs/*.jar
        generate_release_notes: false
